name: Branches

on:
  pull_request:
    branches:
      - '**' # Run on all branches
  push:
    branches:
      - '**' # Run on all branches
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
      - name: Checking out branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      # This will create the directory if it doesn't exist and then decode the keystore from base 64 text representation that we have stored in secrets
      - name: Decode Keystore
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}

        run: |
          mkdir -p $HOME/.android
          chmod +x $HOME/.android
          echo "$SIGNING_KEY_BASE64" | base64 -d > $HOME/.android/release.keystore
          ls -la $HOME/.android # Verify the keystore file is created

      - name: Build Release apk
        run: ./gradlew assembleRelease --stacktrace

      - name: Build Release bundle
        run: ./gradlew bundleRelease --stacktrace

      - name: Get release file aab path
        id: releaseAab
        run: echo "aabfile=$(find app/build/outputs/bundle/release/*.aab)" >> $GITHUB_ENV

      - name: Get release file apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_ENV

      - name: Zip Files
        uses: papeloto/action-zip@v1
        with:
          files: ${{ steps.releaseAab.outputs.aabfile }} ${{ steps.releaseApk.outputs.apkfile }}
          dest: ${{ steps.releaseApk.outputs.apkfile }}.zip

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: ${{ steps.releaseApk.outputs.apkfile }}
