name: Branch

on:
  pull_request:
    branches:
      - '**' # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      ANDROID_SDK_ROOT: /opt/android-sdk
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Decode and Save Signing Key
        run: |
          mkdir -p $HOME/.android
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > $HOME/.android/release.keystore

      - name: Download Dependencies
        run: ./gradlew build --scan --continue

      - name: Assemble Release
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore $HOME/.android/release.keystore \
          -storepass ${{ secrets.SIGNING_STORE_PASSWORD }} \
          -keypass ${{ secrets.SIGNING_KEY_PASSWORD }} \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ secrets.SIGNING_KEY_ALIAS }}

      - name: Verify Signature
        run: jarsigner -verify app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Zipalign APK
        run: ${ANDROID_SDK_ROOT}/build-tools/30.0.3/zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Bump Version Code and Commit
        run: |
          versionCode=$(grep versionCode app/build.gradle.kts | awk '{print $2}')
          newVersionCode=$((versionCode + 1))
          sed -i "s/versionCode $versionCode/versionCode $newVersionCode/" app/build.gradle.kts
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add app/build.gradle.kts
          git commit -m "Bump version code to $newVersionCode"
          git push
